stages:
  - build_push

build_push:
  stage: build_push
  script:
    - echo "Checkout the main branch"
    - echo "Maximize space"
    - echo "Install Just"
    - mkdir -p ~/bin
    - curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/bin
    - export PATH="$PATH:$HOME/bin"
    - just --help
